/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/burgerDouble.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunBottom.geometry}
        material={nodes.bunBottom.material}
        position={[0, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunBottom_1.geometry}
        material={nodes.bunBottom_1.material}
        position={[0, 0.13, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunTop.geometry}
        material={nodes.bunTop.material}
        position={[0, 0.24, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cheese.geometry}
        material={nodes.cheese.material}
        position={[0, 0.07, 0]}
        scale={[2.79, 0.8, 1.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cheese_1.geometry}
        material={nodes.cheese_1.material}
        position={[0, 0.21, 0]}
        scale={[2.79, 0.8, 1.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.patty.geometry}
        material={nodes.patty.material}
        position={[0, 0.06, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.patty_1.geometry}
        material={nodes.patty_1.material}
        position={[0, 0.19, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.salad.geometry}
        material={nodes.salad.material}
        position={[0, 0.04, 0]}
        scale={[0.92, 0.75, 0.92]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.salad_1.geometry}
        material={nodes.salad_1.material}
        position={[0, 0.17, 0]}
        scale={[0.92, 0.6, 0.92]}
      />
      <group position={[0, 0.11, 0]} scale={[1.56, 0.56, 1.56]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_tomato.geometry}
          material={materials._defaultMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_tomato_1.geometry}
          material={materials.red}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/burgerDouble.glb');
