/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/burger.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunBottom.geometry}
        material={nodes.bunBottom.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunTop.geometry}
        material={nodes.bunTop.material}
        position={[0, 0.17, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cheese.geometry}
        material={materials.yellow}
        position={[0, 0.09, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.patty.geometry}
        material={materials.brownDark}
        position={[0, 0.07, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.salad.geometry}
        material={materials.green}
        position={[0, 0.04, 0]}
        scale={[0.92, 0.75, 0.92]}
      />
      <group position={[0, 0.14, 0]} scale={[1.56, 0.7, 1.56]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_tomato.geometry}
          material={materials._defaultMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_tomato_1.geometry}
          material={materials.red}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/burger.glb');
