/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/resources/hotDog.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hotDog.geometry}
        material={materials.brownLight}
      >
        <group position={[0, 0.14, 0]} rotation={[Math.PI, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_sauce.geometry}
            material={materials.yellow}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_sauce_1.geometry}
            material={materials.red}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sausage.geometry}
          material={materials.brown}
          position={[-0.29, 0.09, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.93, 0.93, 0.93]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/resources/hotDog.glb');
