/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/pizza.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.69, 0.87, 0.69]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5.geometry}
          material={nodes.Mesh_slice5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_1.geometry}
          material={nodes.Mesh_slice5_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_2.geometry}
          material={nodes.Mesh_slice5_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_3.geometry}
          material={nodes.Mesh_slice5_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_4.geometry}
          material={nodes.Mesh_slice5_4.material}
        />
      </group>
      <group
        position={[0, 0, 0]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={[0.69, 0.87, 0.69]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5.geometry}
          material={nodes.Mesh_slice5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_1.geometry}
          material={nodes.Mesh_slice5_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_2.geometry}
          material={nodes.Mesh_slice5_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_3.geometry}
          material={nodes.Mesh_slice5_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_4.geometry}
          material={nodes.Mesh_slice5_4.material}
        />
      </group>
      <group
        position={[0, 0, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.69, 0.87, 0.69]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5.geometry}
          material={nodes.Mesh_slice5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_1.geometry}
          material={nodes.Mesh_slice5_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_2.geometry}
          material={nodes.Mesh_slice5_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_3.geometry}
          material={nodes.Mesh_slice5_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_4.geometry}
          material={nodes.Mesh_slice5_4.material}
        />
      </group>
      <group
        position={[0, 0, 0]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.69, 0.87, 0.69]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5.geometry}
          material={nodes.Mesh_slice5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_1.geometry}
          material={nodes.Mesh_slice5_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_2.geometry}
          material={nodes.Mesh_slice5_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_3.geometry}
          material={nodes.Mesh_slice5_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_4.geometry}
          material={nodes.Mesh_slice5_4.material}
        />
      </group>
      <group position={[0, 0, 0]} scale={[0.69, 0.87, 0.69]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5.geometry}
          material={nodes.Mesh_slice5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_1.geometry}
          material={nodes.Mesh_slice5_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_2.geometry}
          material={nodes.Mesh_slice5_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_3.geometry}
          material={nodes.Mesh_slice5_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_4.geometry}
          material={nodes.Mesh_slice5_4.material}
        />
      </group>
      <group
        position={[0, 0, 0]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={[0.69, 0.87, 0.69]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5.geometry}
          material={nodes.Mesh_slice5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_1.geometry}
          material={nodes.Mesh_slice5_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_2.geometry}
          material={nodes.Mesh_slice5_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_3.geometry}
          material={nodes.Mesh_slice5_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_4.geometry}
          material={nodes.Mesh_slice5_4.material}
        />
      </group>
      <group
        position={[0, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.69, 0.87, 0.69]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5.geometry}
          material={nodes.Mesh_slice5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_1.geometry}
          material={nodes.Mesh_slice5_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_2.geometry}
          material={nodes.Mesh_slice5_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_3.geometry}
          material={nodes.Mesh_slice5_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_4.geometry}
          material={nodes.Mesh_slice5_4.material}
        />
      </group>
      <group
        position={[0, 0, 0]}
        rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        scale={[0.69, 0.87, 0.69]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5.geometry}
          material={nodes.Mesh_slice5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_1.geometry}
          material={nodes.Mesh_slice5_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_2.geometry}
          material={nodes.Mesh_slice5_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_3.geometry}
          material={nodes.Mesh_slice5_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_slice5_4.geometry}
          material={nodes.Mesh_slice5_4.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/pizza.glb');
