/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/resources/popsicleChocolate.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_popsicleChocolate.geometry}
        material={materials.brownLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_popsicleChocolate_1.geometry}
        material={materials.purpleLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_popsicleChocolate_2.geometry}
        material={materials.brownDark}
      />
    </group>
  );
}

useGLTF.preload('/resources/popsicleChocolate.glb');
