/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/resources/riceBall.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.89, 0.89, 0.89]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_riceBall.geometry}
          material={materials._defaultMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_riceBall_1.geometry}
          material={materials.brownDarkest}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/resources/riceBall.glb');
