/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/salad.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.93, 0.93, 0.93]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_salad.geometry}
          material={materials.brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_salad_1.geometry}
          material={materials.green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_salad_2.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_salad_3.geometry}
          material={materials.greenDark}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/salad.glb');
