/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/resources/sandwich.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_sandwich.geometry}
          material={materials.brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_sandwich_1.geometry}
          material={materials.brownLight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_sandwich_2.geometry}
          material={nodes.Mesh_sandwich_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lettuce.geometry}
          material={materials.green}
          position={[0.01, 0.07, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meat.geometry}
          material={nodes.meat.material}
          position={[0, 0.08, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/resources/sandwich.glb');
