/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/skewerVegetables.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.skewerVegetables.geometry}
        material={materials.brownLight}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meat.geometry}
          material={nodes.meat.material}
          position={[0.09, 0.01, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.29, 1.29, 1.65]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meat_1.geometry}
          material={nodes.meat_1.material}
          position={[-0.05, 0.01, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.29, 1.29, 1.65]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meat_2.geometry}
          material={nodes.meat_2.material}
          position={[0.22, 0.01, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.29, 1.29, 1.65]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vegetables.geometry}
          material={materials.green}
          position={[0.16, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vegetables_1.geometry}
          material={materials.red}
          position={[0.02, 0, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/skewerVegetables.glb');
