/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/resources/sundae.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_sundae.geometry}
        material={materials._defaultMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_sundae_1.geometry}
        material={materials.purpleLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_sundae_2.geometry}
        material={materials.brownDark}
      />
      <group
        position={[-0.05, 0.54, 0.04]}
        rotation={[Math.PI / 6, 0, 0]}
        scale={[0.62, 0.62, 0.62]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_cherry.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_cherry_1.geometry}
          material={nodes.Mesh_cherry_1.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.straw.geometry}
        material={nodes.straw.material}
        position={[-0.02, 0.56, -0.03]}
        rotation={[-0.26, 0, 0]}
        scale={[0.43, 0.58, 0.43]}
      />
    </group>
  );
}

useGLTF.preload('/resources/sundae.glb');
