/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/resources/sushiSalmon.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sushiSalmon.geometry}
        material={materials._defaultMat}
      >
        <group position={[0, 0.07, 0]} scale={[0.85, 1.69, 1.15]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_salmon.geometry}
            material={materials.orange}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_salmon_1.geometry}
            material={materials.brownLight}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload('/resources/sushiSalmon.glb');
