/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/resources/taco.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_taco.geometry}
        material={materials.brownLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_taco_1.geometry}
        material={materials.yellow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_taco_2.geometry}
        material={materials.red}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_taco_3.geometry}
        material={materials.brownDark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_taco_4.geometry}
        material={materials.green}
      />
    </group>
  );
}

useGLTF.preload('/resources/taco.glb');
