/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/turkey.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.turkey.geometry}
        material={nodes.turkey.material}
      >
        <group
          position={[-0.14, 0, -0.19]}
          rotation={[0, 0.26, 0]}
          scale={[1.3, 1.3, 1.3]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_leg.geometry}
            material={nodes.Mesh_leg.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_leg_1.geometry}
            material={nodes.Mesh_leg_1.material}
          />
        </group>
        <group
          position={[-0.14, 0, 0.19]}
          rotation={[0, -0.26, 0]}
          scale={[1.3, 1.3, 1.3]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_leg_2.geometry}
            material={nodes.Mesh_leg_2.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_leg_3.geometry}
            material={nodes.Mesh_leg_3.material}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload('/turkey.glb');
