/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/wineRed.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wineRed.geometry}
        material={materials.brownDarkest}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wineRed_1.geometry}
        material={materials.brownLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wineRed_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_wineRed_3.geometry}
        material={materials.red}
      />
    </group>
  );
}

useGLTF.preload('/wineRed.glb');
